services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: smartpark
      POSTGRES_PASSWORD: smartpark
      POSTGRES_DB: smartpark
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartpark"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    environment:
      FLASK_ENV: production
      SECRET_KEY: change-me-in-real-deploys-please-32+chars
      DATABASE_URL: postgresql+psycopg://smartpark:smartpark@db:5432/smartpark
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      AUTO_SEED: "1"
      SESSION_COOKIE_SECURE: "0"
    ports:
      - "5000:5000"
    depends_on:
      db: {condition: service_healthy}
      redis: {condition: service_healthy}

  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info -Q smartpark
    environment:
      FLASK_ENV: production
      SECRET_KEY: change-me-in-real-deploys-please-32+chars
      DATABASE_URL: postgresql+psycopg://smartpark:smartpark@db:5432/smartpark
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db: {condition: service_healthy}
      redis: {condition: service_healthy}

  beat:
    build: .
    command: celery -A celery_worker.celery beat --loglevel=info
    environment:
      FLASK_ENV: production
      SECRET_KEY: change-me-in-real-deploys-please-32+chars
      DATABASE_URL: postgresql+psycopg://smartpark:smartpark@db:5432/smartpark
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
    depends_on:
      db: {condition: service_healthy}
      redis: {condition: service_healthy}

volumes:
  pgdata:
